runtime: nodejs14
service: default

instance_class: F1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 0.030s
  max_instances: 1

handlers:
  - url: /.*
    secure: always
    script: auto
